apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devbox.fullname" . }}-postgres-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devbox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
