apiVersion: v1
kind: Service
metadata:
  name: {{ include "devbox.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    app: {{ include "devbox.fullname" . }}-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
