import type { InsertEnvironmentTemplate } from "../drizzle/schema";

export const builtinTemplateSeeds: InsertEnvironmentTemplate[] = [
  {
    name: "Node.js Workspace",
    slug: "node",
    description:
      "Node.js 22 workspace with npm and a development server entrypoint.",
    runtime: "node",
    image: "node:22-bookworm-slim",
    defaultCpu: "500m",
    maxCpu: "2",
    defaultMemory: "1Gi",
    maxMemory: "4Gi",
    defaultStorage: "5Gi",
    maxStorage: "20Gi",
    allowedPorts: [3000, 4173, 5173, 8080],
    configurationSchema: { packageManager: ["npm"], workdir: "/workspace" },
    active: "true",
  },
  {
    name: "Python Workspace",
    slug: "python",
    description:
      "Python 3.12 workspace with pip and a configurable application port.",
    runtime: "python",
    image: "python:3.12-slim",
    defaultCpu: "500m",
    maxCpu: "2",
    defaultMemory: "1Gi",
    maxMemory: "4Gi",
    defaultStorage: "5Gi",
    maxStorage: "20Gi",
    allowedPorts: [5000, 8000, 8080, 8888],
    configurationSchema: { packageManager: ["pip"], workdir: "/workspace" },
    active: "true",
  },
  {
    name: "Go Workspace",
    slug: "go",
    description:
      "Go 1.23 workspace designed for lightweight services and tooling.",
    runtime: "go",
    image: "golang:1.23-bookworm",
    defaultCpu: "500m",
    maxCpu: "2",
    defaultMemory: "1Gi",
    maxMemory: "4Gi",
    defaultStorage: "5Gi",
    maxStorage: "20Gi",
    allowedPorts: [3000, 8080, 8081, 9090],
    configurationSchema: { packageManager: ["go"], workdir: "/workspace" },
    active: "true",
  },
  {
    name: "Ubuntu Workspace",
    slug: "ubuntu",
    description:
      "Ubuntu 24.04 workspace for controlled, general-purpose developer workloads.",
    runtime: "ubuntu",
    image: "ubuntu:24.04",
    defaultCpu: "250m",
    maxCpu: "2",
    defaultMemory: "512Mi",
    maxMemory: "4Gi",
    defaultStorage: "5Gi",
    maxStorage: "20Gi",
    allowedPorts: [3000, 8000, 8080, 8888],
    configurationSchema: { shell: ["bash"], workdir: "/workspace" },
    active: "true",
  },
];
