apiVersion: v1
kind: Service
metadata:
  name: cnad32
  namespace: cnad32-platform
spec:
  selector:
    app.kubernetes.io/name: cnad32
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
